/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

export function Fauna(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/jungle-merged.glb') as any;
  return (
    <group {...props} dispose={null}>
      <group
        position={[2.49908357, -1.63235712, 0.355537408]}
        rotation={[Math.PI, -0.4054188, Math.PI]}
        scale={[0.03400108, 0.03400107, 0.03400108]}
        userData={{ name: 'Fauna' }}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331.geometry} material={materials['Material #35.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331_1.geometry} material={materials['Material #38.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331_2.geometry} material={materials['Material #33.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331_3.geometry} material={materials['Material #32.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331_4.geometry} material={materials['Material #288.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331_5.geometry} material={materials['Material #26.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331_6.geometry} material={materials['Material #33']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331_7.geometry} material={materials['Material #32']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh1331_8.geometry} material={materials['Material #288']} />
      </group>
    </group>
  );
}

useGLTF.preload('/jungle-merged.glb');
