/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        环体: THREE.Mesh
        柱体015: THREE.Mesh
        柱体016: THREE.Mesh
        柱体017: THREE.Mesh
        柱体018: THREE.Mesh
        球体019: THREE.Mesh
        球体020: THREE.Mesh
        柱体020: THREE.Mesh
        柱体021: THREE.Mesh
        柱体022: THREE.Mesh
        球体021: THREE.Mesh
        柱体023: THREE.Mesh
        棱角球002: THREE.Mesh
        棱角球003: THREE.Mesh
        球体022: THREE.Mesh
        球体023: THREE.Mesh
        柱体024: THREE.Mesh
        球体024: THREE.Mesh
        球体025: THREE.Mesh
        柱体025: THREE.Mesh
        柱体026: THREE.Mesh
        球体028: THREE.Mesh
        柱体027: THREE.Mesh
        球体029: THREE.Mesh
        柱体028: THREE.Mesh
        球体030: THREE.Mesh
        柱体029: THREE.Mesh
        球体031: THREE.Mesh
        立方体006: THREE.Mesh
        立方体009: THREE.Mesh
        立方体009_1: THREE.Mesh
        立方体010: THREE.Mesh
        立方体011: THREE.Mesh
        球体032: THREE.Mesh
        球体033: THREE.Mesh
        球体034: THREE.Mesh
        球体035: THREE.Mesh
        球体036: THREE.Mesh
        球体037: THREE.Mesh
        ball038: THREE.Mesh
        球体039: THREE.Mesh
        球体040: THREE.Mesh
        球体041: THREE.Mesh
        球体042: THREE.Mesh
        球体043: THREE.Mesh
        球体044: THREE.Mesh
        球体045: THREE.Mesh
        球体046: THREE.Mesh
        球体047: THREE.Mesh
        球体048: THREE.Mesh
        球体049: THREE.Mesh
        Star: THREE.Mesh
        柱体030: THREE.Mesh
        Star001: THREE.Mesh
        柱体031: THREE.Mesh
        logo: THREE.Mesh
        柱体019: THREE.Mesh
        NURBS_曲线001: THREE.Mesh
    }
    materials: {
        ornage: THREE.MeshPhysicalMaterial
        three: THREE.MeshPhysicalMaterial
        wood: THREE.MeshPhysicalMaterial
        snow: THREE.MeshPhysicalMaterial
        black: THREE.MeshPhysicalMaterial
        gun: THREE.MeshStandardMaterial
        ["black.001"]: THREE.MeshPhysicalMaterial
        gift: THREE.MeshPhysicalMaterial
        ["ornage.001"]: THREE.MeshPhysicalMaterial
        star: THREE.MeshPhysicalMaterial
        logo: THREE.MeshStandardMaterial
        ["suger.001"]: THREE.MeshPhysicalMaterial
    }
};

export function Model(props: JSX.IntrinsicElements["group"]) {
    const {
        nodes,
        materials
    } = useGLTF("/model.glb") as unknown as GLTFResult;

    return (<group {...props} dispose={null}>
        <mesh geometry={nodes.环体.geometry} material={materials.ornage} position={[1.07, 2.38, 0.73]} rotation={[0.41, -0.53, -1.28]} scale={0.21} />
        <mesh geometry={nodes.柱体015.geometry} material={materials.three} position={[-0.73, 2.79, -1.05]} rotation={[-0.17, -0.02, 0.13]} scale={0.3} />
        <mesh geometry={nodes.柱体016.geometry} material={materials.three} position={[-0.67, 2.35, -0.97]} rotation={[-0.17, -0.02, 0.13]} scale={0.35} />
        <mesh geometry={nodes.柱体017.geometry} material={materials.three} position={[-0.6, 1.81, -0.88]} rotation={[-0.17, -0.02, 0.13]} scale={0.45} />
        <mesh geometry={nodes.柱体018.geometry} material={materials.wood} position={[-0.62, 1.92, -0.9]} rotation={[-0.17, -0.02, 0.13]} scale={0.12} />
        <mesh geometry={nodes.球体019.geometry} material={materials.three} position={[-0.57, 1.59, -0.84]} rotation={[-0.17, -0.02, 0.13]} scale={0.31} />
        <mesh geometry={nodes.球体020.geometry} material={materials.snow} position={[0, 1.86, 0]} />
        <mesh geometry={nodes.柱体020.geometry} material={materials.three} position={[0.7, 2.16, -1.11]} rotation={[-0.22, -0.01, -0.13]} scale={0.24} material-color={"rgb(85, 32, 32)"} />
        <mesh geometry={nodes.柱体021.geometry} material={materials.three} position={[0.65, 1.81, -1.03]} rotation={[-0.22, -0.01, -0.13]} scale={0.28} />
        <mesh geometry={nodes.柱体022.geometry} material={materials.wood} position={[0.63, 1.71, -1]} rotation={[-0.22, -0.01, -0.13]} scale={0.07} />
        <mesh geometry={nodes.球体021.geometry} material={materials.three} position={[0.61, 1.49, -0.96]} rotation={[-0.22, -0.01, -0.13]} scale={0.2} />
        <mesh geometry={nodes.柱体023.geometry} material={materials.wood} position={[0.56, 1.45, -0.92]} rotation={[-0.13, 0, -1.27]} scale={-0.04} />
        <mesh geometry={nodes.棱角球002.geometry} material={materials.snow} position={[0.7, 1.67, 0.45]} rotation={[0, 0.71, 0]} scale={[0.66, 0.64, 0.66]} />
        <mesh geometry={nodes.棱角球003.geometry} material={materials.snow} position={[0.78, 2.44, 0.54]} rotation={[0, 0.71, 0]} scale={[0.43, 0.42, 0.43]} />
        <mesh geometry={nodes.球体022.geometry} material={materials.black} position={[1.14, 1.81, 0.87]} scale={0.05} />
        <mesh geometry={nodes.球体023.geometry} material={materials.black} position={[1.1, 1.98, 0.82]} scale={0.05} />
        <mesh geometry={nodes.柱体024.geometry} material={materials.ornage} position={[1.08, 2.39, 0.74]} rotation={[1.7, -0.15, -0.88]} scale={0.08} />
        <mesh geometry={nodes.球体024.geometry} material={materials.black} position={[1, 2.51, 0.86]} scale={[0.06, 0.06, 0.04]} />
        <mesh geometry={nodes.球体025.geometry} material={materials.black} position={[1.12, 2.52, 0.68]} rotation={[-0.21, 0, -0.12]} scale={[0.07, 0.07, 0.05]} />
        <mesh geometry={nodes.柱体025.geometry} material={materials.black} position={[0.66, 2.9, 0.53]} rotation={[0.02, -0.01, 0.29]} scale={0.37} />
        <mesh geometry={nodes.柱体026.geometry} material={nodes.柱体026.material} position={[0.47, 1.34, 0.65]} rotation={[0, 0.71, 2.46]} scale={0.03} />
        <mesh geometry={nodes.球体028.geometry} material={nodes.球体028.material} position={[0.36, 1.18, 0.74]} rotation={[0, 0.71, 2.46]} scale={0.22} />
        <mesh geometry={nodes.柱体027.geometry} material={materials.gun} position={[0.33, 1.87, 0.77]} rotation={[0, 0.71, 1.15]} scale={0.02} />
        <mesh geometry={nodes.球体029.geometry} material={nodes.球体029.material} position={[0.24, 1.93, 0.85]} rotation={[0, 0.71, 1.15]} scale={0.15} />
        <mesh geometry={nodes.柱体028.geometry} material={nodes.柱体028.material} position={[0.94, 1.34, 0.24]} rotation={[-Math.PI, -0.71, 2.46]} scale={-0.03} />
        <mesh geometry={nodes.球体030.geometry} material={nodes.球体030.material} position={[1.05, 1.18, 0.16]} rotation={[-Math.PI, -0.71, 2.46]} scale={-0.22} />
        <mesh geometry={nodes.柱体029.geometry} material={materials.gun} position={[1.07, 1.87, 0.13]} rotation={[-Math.PI, -0.71, 1.15]} scale={-0.02} />
        <mesh geometry={nodes.球体031.geometry} material={nodes.球体031.material} position={[1.17, 1.93, 0.05]} rotation={[-Math.PI, -0.71, 1.15]} scale={-0.15} />
        <mesh geometry={nodes.立方体006.geometry} material={materials["black.001"]} position={[-0.82, 1.5, 0.47]} rotation={[0, 0.22, 0.05]} scale={[0.45, 0.28, 0.45]} />
        <group position={[-0.85, 1.93, 0.46]} rotation={[0, 0.22, 0.05]} scale={[0.5, 0.22, 0.5]}>
            <mesh geometry={nodes.立方体009.geometry} material={materials.gift} />
            <mesh geometry={nodes.立方体009_1.geometry} material={materials["ornage.001"]} />
        </group>
        <mesh geometry={nodes.立方体010.geometry} material={materials["ornage.001"]} position={[-0.82, 1.5, 0.47]} rotation={[0, 0.22, 0.05]} scale={[0.46, 0.28, 0.46]} />
        <mesh geometry={nodes.立方体011.geometry} material={materials["ornage.001"]} position={[-0.82, 1.48, 0.47]} rotation={[-2.96, 1.36, 2.95]} scale={[0.46, 0.28, 0.46]} />
        <mesh geometry={nodes.球体032.geometry} material={materials.three} position={[-0.58, 0.95, 1.08]} rotation={[-0.19, 0.16, 2.16]} scale={0.4} />
        <mesh geometry={nodes.球体033.geometry} material={materials.three} position={[-0.24, 1, 1.15]} rotation={[-0.19, 0.16, 2.16]} scale={0.47} />
        <mesh geometry={nodes.球体034.geometry} material={materials.three} position={[1.41, 0.77, -0.17]} rotation={[-0.19, 0.16, 2.16]} scale={0.47} />
        <mesh geometry={nodes.球体035.geometry} material={materials.three} position={[1.27, 1.01, -0.33]} rotation={[-0.19, 0.16, 2.16]} scale={0.32} />
        <mesh geometry={nodes.球体036.geometry} material={materials.three} position={[0.74, 0.72, 1.15]} rotation={[0.21, -0.37, 1.39]} scale={-0.5} />
        <mesh geometry={nodes.球体037.geometry} material={materials.three} position={[-1.44, 1.01, -0.07]} rotation={[-0.19, 0.16, 2.16]} scale={0.26} />
        <mesh geometry={nodes.ball038.geometry} material={materials.snow} position={[-0.75, 2.91, -0.73]} scale={-0.09} />
        <mesh geometry={nodes.球体039.geometry} material={materials.snow} position={[-1, 2.39, -1.18]} scale={-0.13} />
        <mesh geometry={nodes.球体040.geometry} material={materials.snow} position={[-0.41, 1.85, -1.39]} scale={-0.13} />
        <mesh geometry={nodes.球体041.geometry} material={materials.snow} position={[-0.72, 2.96, -1.31]} scale={-0.13} />
        <mesh geometry={nodes.球体042.geometry} material={materials.snow} position={[-0.14, 2.02, -0.64]} scale={-0.11} />
        <mesh geometry={nodes.球体043.geometry} material={materials.snow} position={[-0.3, 2.48, -1.1]} scale={-0.11} />
        <mesh geometry={nodes.球体044.geometry} material={materials.snow} position={[-0.89, 2, -0.44]} scale={-0.08} />
        <mesh geometry={nodes.球体045.geometry} material={materials.snow} position={[0.73, 2.33, -1.36]} scale={-0.04} />
        <mesh geometry={nodes.球体046.geometry} material={materials.snow} position={[0.33, 1.85, -1.18]} scale={-0.08} />
        <mesh geometry={nodes.球体047.geometry} material={materials.snow} position={[0.83, 2.3, -0.92]} scale={-0.08} />
        <mesh geometry={nodes.球体048.geometry} material={materials.snow} position={[0.98, 1.78, -1.17]} scale={-0.08} />
        <mesh geometry={nodes.球体049.geometry} material={materials.snow} position={[0.54, 1.93, -0.73]} scale={-0.08} />
        <mesh geometry={nodes.Star.geometry} material={materials.star} position={[-0.83, 3.52, -1.21]} rotation={[-0.08, -0.84, -1.32]} scale={0.22} />
        <mesh geometry={nodes.柱体030.geometry} material={materials.gun} position={[-0.81, 3.27, -1.17]} scale={0.03} />
        <mesh geometry={nodes.Star001.geometry} material={materials.star} position={[0.78, 2.74, -1.24]} rotation={[-2.97, -1.23, 2.05]} scale={0.17}></mesh>
        <mesh geometry={nodes.柱体031.geometry} material={materials.gun} position={[0.76, 2.55, -1.21]} rotation={[0, -1.07, 0]} scale={0.02} />
        <mesh geometry={nodes.logo.geometry} material={materials.logo} position={[-0.87, 2.15, 0.45]} rotation={[0.07, -0.66, 0.07]} scale={0.48} />
        <mesh geometry={nodes.柱体019.geometry} material={materials["suger.001"]} position={[0, 0.4, 0]} />
        <mesh geometry={nodes.NURBS_曲线001.geometry} material={materials["suger.001"]} position={[-1.5, 1.61, -0.59]} rotation={[1.45, 0.28, -2.39]} scale={0.36} />
    </group>);
}

useGLTF.preload("/model.glb");